export const INGREDIENTS_GET_REQUESTED = 'INGREDIENTS_GET_REQUESTED';
export const INGREDIENTS_GET_FAILED = 'INGREDIENTS_GET_FAILED';
export const INGREDIENTS_GET_SUCCEED = 'INGREDIENTS_GET_SUCCEED';
